module ExtractTtc
  module Constants
    TTC_TAG: String

    TTC_VERSION_1: Integer

    TTC_VERSION_2: Integer

    HEAD_TAG: String

    CHECKSUM_ADJUSTMENT_MAGIC: Integer

    SUPPORTED_VERSIONS: Array[Integer]

    TABLE_ALIGNMENT: Integer
  end
end