inherit_from:
  - 'https://raw.githubusercontent.com/fontist/oss-guides/master/ci/rubocop.yml'

AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

Gemspec/RequireMFA:
  Enabled: false
