inherit_from:
  - https://raw.githubusercontent.com/riboseinc/oss-guides/main/ci/rubocop.yml
  - .rubocop_todo.yml

# local repo-specific modifications
# ...

# AllCops:
#   TargetRubyVersion: 3.0
#   NewCops: enable
