name: rspec

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Test on Ruby ${{ matrix.ruby }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.7', '3.0', '3.1' ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        experimental: [ false ]

    steps:
      - uses: actions/checkout@master

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-${{ matrix.os }}-${{ matrix.ruby }}-${{ hashFiles('**/*.gemspec') }}
          restore-keys: bundle-${{ matrix.os }}-${{ matrix.ruby }}

      - run: bundle config set path 'vendor/bundle'

      - run: bundle install --jobs 4 --retry 3

      - run: bundle exec rake compile

      - run: bundle exec rake